import { FormEvent, useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export default function AccountPage() {
  const {user,loading,login,register,logout}=useAuth(); const [mode,setMode]=useState<'login'|'register'>('login'); const [error,setError]=useState('');
  const [form,setForm]=useState({name:'',email:'',phone:'',password:''});
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{mode==='login'?await login(form.email,form.password):await register(form);}catch(err){setError(err instanceof Error?err.message:'Unable to continue')}};
  if(user) return <main className="min-h-[70vh] px-4 py-16"><section className="section-shell mx-auto max-w-xl text-center"><img src="/brand/achari-tiwari-logo.png" alt="Achari Tiwari" className="mx-auto mb-5 h-28 w-28 rounded-full object-cover"/><p className="text-sm font-bold uppercase tracking-widest text-primary">Your account</p><h1 className="mt-2 text-3xl font-bold">Namaste, {user.name}</h1><p className="mt-3 text-muted-foreground">{user.email}</p><Button onClick={logout} variant="outline" className="mt-8">Sign out</Button></section></main>;
  return <main className="min-h-[75vh] px-4 py-12"><section className="section-shell mx-auto max-w-lg"><div className="text-center"><img src="/brand/achari-tiwari-logo.png" alt="Achari Tiwari" className="mx-auto h-24 w-24 rounded-full object-cover"/><h1 className="mt-4 text-3xl font-bold">{mode==='login'?'Welcome back':'Create your account'}</h1><p className="mt-2 text-sm text-muted-foreground">You can also continue as a guest during checkout.</p></div><form onSubmit={submit} className="mt-8 space-y-4">{mode==='register'&&<><div><Label>Name</Label><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><Label>Mobile number</Label><Input required inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div></>}<div><Label>Email</Label><Input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>Password</Label><Input required minLength={6} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button disabled={loading} className="w-full">{loading?'Please wait…':mode==='login'?'Sign in':'Register'}</Button></form><button onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}} className="mt-5 w-full text-sm font-semibold text-primary">{mode==='login'?'New here? Create an account':'Already registered? Sign in'}</button></section></main>;
}
