import { Check, PackageOpen } from 'lucide-react';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
import type { ProductVariant } from '@/lib/productVariants';

const variantKey=(variant:ProductVariant,index:number)=>variant.sku||variant.id||String(index);
const DefaultBadge=()=> <span className="border border-[#8b1e2d]/30 bg-[#8b1e2d]/10 px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wider text-[#8b1e2d]">Default</span>;

export function VariantPicker({variants,value,onChange,label='Choose your pack'}:{variants:ProductVariant[];value?:string;onChange:(variant:ProductVariant)=>void;label?:string}) {
  const byKey=new Map(variants.map((variant,index)=>[variantKey(variant,index),variant]));
  return <fieldset><legend className="mb-3 text-sm font-bold text-foreground">{label}</legend><RadioGroupPrimitive.Root value={value} onValueChange={key=>{const variant=byKey.get(key);if(variant?.inStock)onChange(variant)}} aria-label={label} className="grid gap-2 sm:grid-cols-2">{variants.map((variant,index)=>{const key=variantKey(variant,index);const selected=key===value;return <RadioGroupPrimitive.Item key={key} value={key} disabled={!variant.inStock} aria-label={`${variant.label}${variant.isDefault?', default pack':''}${variant.size&&variant.size!==variant.label?`, ${variant.size}`:''}, ₹${variant.price}${variant.inStock?`, ${variant.inventory} available`:', out of stock'}`} className={`relative min-h-16 border p-3 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#b58a3c] focus-visible:ring-offset-2 ${selected?'border-[#b58a3c] bg-[#fff8e8] shadow-[inset_3px_0_0_#b58a3c]':'border-[#d8c9af] bg-[#fffdf8] hover:border-[#b58a3c]'} disabled:cursor-not-allowed disabled:bg-[#eee8dc] disabled:text-muted-foreground`}><span className="flex items-start justify-between gap-3"><span><span className="flex items-center gap-2 font-bold">{variant.label}{variant.isDefault?<DefaultBadge/>:null}</span>{variant.size&&variant.size!==variant.label?<span className="mt-0.5 block text-xs text-muted-foreground">{variant.size}</span>:null}<span className="mt-1 block text-xs">{variant.inStock?`${variant.inventory} available`:'Out of stock'}</span></span><span className="text-right"><span className="block font-display text-xl text-primary">₹{variant.price.toLocaleString('en-IN')}</span>{selected?<Check className="ml-auto mt-1 h-4 w-4 text-[#8a641e]" aria-hidden="true"/>:<PackageOpen className="ml-auto mt-1 h-4 w-4 text-muted-foreground" aria-hidden="true"/>}</span></span></RadioGroupPrimitive.Item>})}</RadioGroupPrimitive.Root></fieldset>;
}
